Added Sky Dimension (description)
Dimension currently desert biome with all vanilla stuff.

BUT get this error when ever you touch the portal

2013-02-01 16:17:52 [INFO] [STDERR]
net.minecraft.util.ReportedException: Ticking entity
2013-02-01 16:17:52 [INFO] [STDERR]  at
net.minecraft.world.World.updateEntities(World.java:2123)
2013-02-01 16:17:52 [INFO] [STDERR]  at
net.minecraft.client.Minecraft.runTick(Minecraft.java:1863)
2013-02-01 16:17:52 [INFO] [STDERR]  at
net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:846)
2013-02-01 16:17:52 [INFO] [STDERR]  at
net.minecraft.client.Minecraft.run(Minecraft.java:771)
2013-02-01 16:17:52 [INFO] [STDERR]  at java.lang.Thread.run(Unknown
Source)
2013-02-01 16:17:52 [INFO] [STDERR] Caused by:
java.lang.ClassCastException:
net.minecraft.client.entity.EntityClientPlayerMP cannot be cast to
net.minecraft.entity.player.EntityPlayerMP
2013-02-01 16:17:52 [INFO] [STDERR]  at
skycraft.blocks.PortalBlock.onEntityCollidedWithBlock(PortalBlock.java:45)
2013-02-01 16:17:52 [INFO] [STDERR]  at
net.minecraft.entity.Entity.doBlockCollisions(Entity.java:1011)
2013-02-01 16:17:52 [INFO] [STDERR]  at
net.minecraft.entity.Entity.moveEntity(Entity.java:955)
2013-02-01 16:17:52 [INFO] [STDERR]  at
net.minecraft.client.entity.EntityPlayerSP.moveEntity(EntityPlayerSP.java:95)
2013-02-01 16:17:52 [INFO] [STDERR]  at
net.minecraft.entity.EntityLiving.moveEntityWithHeading(EntityLiving.java:1536)
2013-02-01 16:17:52 [INFO] [STDERR]  at
net.minecraft.entity.player.EntityPlayer.moveEntityWithHeading(EntityPlayer.java:1793)
2013-02-01 16:17:52 [INFO] [STDERR]  at
net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:1824)
2013-02-01 16:17:52 [INFO] [STDERR]  at
net.minecraft.entity.player.EntityPlayer.onLivingUpdate(EntityPlayer.java:560)
2013-02-01 16:17:52 [INFO] [STDERR]  at
net.minecraft.client.entity.EntityPlayerSP.onLivingUpdate(EntityPlayerSP.java:278)
2013-02-01 16:17:52 [INFO] [STDERR]  at
net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:843)
2013-02-01 16:17:52 [INFO] [STDERR]  at
net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:328)
2013-02-01 16:17:52 [INFO] [STDERR]  at
net.minecraft.client.entity.EntityClientPlayerMP.onUpdate(EntityClientPlayerMP.java:76)
2013-02-01 16:17:52 [INFO] [STDERR]  at
net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2291)
2013-02-01 16:17:52 [INFO] [STDERR]  at
net.minecraft.world.World.updateEntity(World.java:2253)
2013-02-01 16:17:52 [INFO] [STDERR]  at
net.minecraft.world.World.updateEntities(World.java:2107)
2013-02-01 16:17:52 [INFO] [STDERR]  ... 4 more